### ISSUE TITLE
Panic on leptos 0.5.2

### ISSUE THREAD

**Issue by circuitsacul** [nicoburniske/leptos_query#17]
My code was just calling `use_query` with a server fn as the input. I'm not really sure what the problem is, but here's the spantrace + backtrace.

The last line is `fatal runtime error: thread local panicked on drop`, and there's multiple mentions of thread local.

https://hastebin.skyra.pw/ubixepupur.swift

**Comment by stefanboere** [comment]
Hi,
I had the same  issue, but the solution is section in the FAQ; 
https://github.com/nicoburniske/leptos_query/blob/main/FAQ.md#why-am-i-getting-a-panic-on-my-leptos-main-function

**Comment by nicoburniske** [comment]
Can you provide a reproducer?

**Comment by stefanboere** [comment]
Hi, I also got this same error message, but it turned out to be just the panic from the FAQ https://github.com/nicoburniske/leptos_query/blob/main/FAQ.md#why-am-i-getting-a-panic-on-my-leptos-main-function. `supress_query_load` around the generate_route_list solved the issue.
