### ISSUE TITLE
Island and/or workspace make leptos_query unusable

### ISSUE THREAD

**Issue by vincentberthier** [nicoburniske/leptos_query#23]
I’ve separated my project into crates (app/frontend/server) and I’m using islands, but sadly leptos_query really doesn’t like something there as any one of them gives an error:
![image](https://github.com/nicoburniske/leptos_query/assets/34085617/ab414bfe-d05a-42fc-bc0d-731c51cd1225)

I’ve created a toy example to showcase this at https://github.com/VincentBerthier/leptos-repro/tree/query

**Comment by vincentberthier** [comment]
I’m told it might be a bug in Leptos’ Suspenses. TBC.

**Comment by nicoburniske** [comment]
Added an example for using leptos_query with axum workspace 

leptos_query/example/leptos-query-axum-workspace

Islands will not be supported until Leptos 0.7 comes out. It seems too buggy and difficult atm
