### ISSUE TITLE
 I would like to know more about how to use IndexedDB

### ISSUE THREAD

**Issue by sideproject0214** [nicoburniske/leptos_query#33]
Hello. I'm a beginner lepto user with a keen interest in leptos-query. First of all, thank you for creating such a great library.

I want to implement infinite scrolling using use_intersection_observer from leptos-use and leptos-query. I've implemented infinite scroll itself, but I'm facing an issue where all the data disappears when I select a specific item, navigate to its page, and then return to the original infinite scroll page. I need to fetch the data again.

To solve this, my initial thought was to use use_query to retrieve the data, store it via provide_context, and then merge the previous and current data into a vector to display. However, all the previously received data disappeared.

Therefore, I want to implement a method to retrieve data stored in IndexedDB, but it's proving to be more difficult than expected, hence this message. Could you please briefly explain how to implement data retrieval from IndexedDB?

※ Do you have any plans to implement infinite-loading APIs similar to tanstack query?

**Comment by nicoburniske** [comment]
You can use the indexdb query persister to do this pretty easily. There are two features available, one for LocalStorage and one for IndexedDB. This will automatically persist and retrieve your data on page load. 

In your Cargo.toml add the feature `indexed_db`.

```toml
# add the relevant feature here. you can also add "local_storage"
leptos_query = { version = "0.5" features = [ "indexed_db"] }
```
In your leptos App add this line instead of the normal `provide_query_client`

```rust
 // Provides Query Client for entire app.
provide_query_client_with_options_and_persister(
    Default::default(),
    query_persister::IndexedDbPersister,
);
```

You can look at the implementation here

https://github.com/gaucho-labs/leptos-query/blob/main/query/src/query_persister/indexed_db.rs 

I don't have any plans to implement infinite scroll yet

**Comment by sideproject0214** [comment]
Thank you very much. The reason for the delayed response is that I am not familiar with Rust and Leptos.

Here's a summary of the code I've tried, although I'm not sure if I've done it correctly, here are some code snippets and suggestions for others who may be looking at this.

**0. Setting**
```rust
#[component]
pub fn App() -> impl IntoView {
  let persister =
    query_persister::IndexedDbPersister::new("fmtf".to_string(), "fmtf_cache".to_string());

  provide_query_client_with_options_and_persister(Default::default(), persister);
  provide_meta_context();

  view! {
    <LeptosQueryDevtools/>
    <Stylesheet id="leptos" href="/pkg/ABCD.css"/>
    <Title text="ABCD"/>
    <Router>
      <main>
        <Routes>
          <Route path="/" view=VideosHome/>
        </Routes>
      </main>
      <Footer/>
    </Router>
  }
}
```

Here, it's important to note that you must define the database_name and object_store names through **query_persister::IndexedDbPersister::new**. In my case, I defined them as fmtf and fmtf_cache.

**1. Key Definition**

```rust
#[derive(Hash, PartialEq, Eq, Clone, Copy, Debug, Serialize, Deserialize)]
pub struct PageNum(pub i32);
```

**2. Definition of MyPersistQueryData**
   (1). Docs address : <https://docs.rs/leptos_query/0.5.3/leptos_query/query_persister/struct.PersistQueryData.html>

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyPersistQueryData {
  pub value: String,
  pub updated_at: u64,
}

impl PageNum {
  pub fn get(&self) -> i32 {
    self.0
  }
}
```

(Issue) Originally, PersistQueryData should be usable alone. However, since the Debug trait is not implemented, when setting up create_query with QueryOptions::default(), the following error occurs:

_PersistQueryData doesn't implement std::fmt::Debug the trait std::fmt::Debug is not implemented for PersistQueryData, which is required by std::option::Option<PersistQueryData>: QueryValue required for std::option::Option<PersistQueryData> to implement std::fmt::Debug required for std::option::Option<PersistQueryData> to implement `QueryValue_

So, I created MyPersistQueryData separately.

(Solution) Adding Debug to PersistQueryData should resolve it.

PersistQueryData doesn't implement std::fmt::Debug the trait std::fmt::Debug is not implemented for PersistQueryData, which is required by std::option::Option<PersistQueryData>: QueryValue required for std::option::Option<PersistQueryData> to implement std::fmt::Debug required for std::option::Option<PersistQueryData> to implement `QueryValue

```rust
/// Serialized query data.
#[derive(Clone, Debug)]
#[cfg_attr(
    any(feature = "local_storage", feature = "indexed_db"),
    derive(miniserde::Serialize, miniserde::Deserialize)
)]
pub struct PersistQueryData {
    /// The serialized query data.
    pub value: String,
    /// The time the query was last updated in millis.
    pub updated_at: u64,
}
```

**3. create_query**

```rust
pub async fn use_db_retrieve(s: String) -> Option<MyPersistQueryData> {
  let persister =
    query_persister::IndexedDbPersister::new("fmtf".to_string(), "fmtf_cache".to_string());

  let result = persister.retrieve(&s).await;

  result.map(|data| MyPersistQueryData {
    value: data.value,
    updated_at: data.updated_at,
  })
}

pub fn get_indexed_db_query() -> QueryScope<String, Option<MyPersistQueryData>> {
  create_query(use_db_retrieve, QueryOptions::default())
}
```
To retrieve data stored in indexedDB, you need to use **retrieve**, where the key is &str. Therefore, I initially accepted the parameter as String and then changed it to a referencing format due to lifetimes.

```rust
fn retrieve<'life0, 'life1, 'async_trait>(
    &'life0 self,
    key: &'life1 str
) -> Pin<Box<dyn Future<Output = Option<PersistQueryData>> + 'async_trait>>
where
    Self: 'async_trait,
    'life0: 'async_trait,
    'life1: 'async_trait,
```

**4. Receiving Data**

```rust
  let page_size_str = move || format!("PageNum({})", page_size.get().get());

  let QueryResult {
    data: indexed_db, ..
  } = get_indexed_db_query().use_query(move || page_size_str());

  logging::log!(
      "indexed_db: {:#?},page_size_str {:?}",
      indexed_db.get(),
      page_size_str()
    );
```

Be mindful that the key is stored as String. Since I defined **PageNum(pub i32)** as above, keys are stored as 'PageNum(0)', 'PageNum(1)', and so on. Therefore, I defined the key value using the format! macro as shown above.

Additionally, when outputting this to the log, you can confirm the values stored in indexedDB.

※ The above is the method I used. Please feel free to point out any strange parts.

**Comment by nicoburniske** [comment]
You don't need to explicitly retrieve things from IndexedDb.

Your query should be fetching data from somewhere (e.g. a leptos server function). When a query is mounted, `leptos_query` will automatically check if that key's data exists in a persister. [Here's the source code 
](https://github.com/gaucho-labs/leptos-query/blob/b459583019c5dc4d6c70754a0df1dd930c674ab1/query/src/query_cache.rs#L156) 

When a query is executed, the data is then stored into the persister automatically.

**Comment by sideproject0214** [comment]
I used to think that simply receiving data and saving it to indexedDB was enough, but after looking at the source code, I realized that was a misconception. Thank you very much~~~

**Comment by nicoburniske** [comment]
No problem. Will close as resolved
